version: "3"

services:
  node:
    image: node
    container_name: nodejs
    user: "node"
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3001:3001"
    command: "npm run dev"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor

volumes:
  dbdata:
